"""adding transactions

Revision ID: 15a48ae967ac
Revises: 6ca1d9d97a95
Create Date: 2019-08-06 21:51:41.610248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from models import transaction
# revision identifiers, used by Alembic.
revision = '15a48ae967ac'
down_revision = '6ca1d9d97a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('line_items', postgresql.ARRAY(transaction.LineItemType()), server_default='{}', nullable=True),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
