"""changing line item type

Revision ID: 5fcbd01398c9
Revises: 15a48ae967ac
Create Date: 2019-08-11 00:52:03.455503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, ARRAY

# revision identifiers, used by Alembic.
revision = '5fcbd01398c9'
down_revision = '15a48ae967ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'line_items')
    op.add_column('transactions', sa.Column('line_items', JSONB, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'line_items')
    op.add_column('transactions', sa.Column('line_items', ARRAY(JSONB), nullable=True, server_default='{}'))
    # ### end Alembic commands ###
